### ISSUE TITLE
Ubuntu下执行报错

### ISSUE THREAD

**Issue by HeyGoda** [chen-shang/BaseShell#1]
xyz@ubuntu:~/work_tools/shell$ sh $(pwd)/BaseShell/init.sh
project[项目目录]:com.baseshell.learn
/home/xyz/work_tools/shell/BaseShell/init.sh: 5: /home/xyz/work_tools/shell/BaseShell/init.sh: [[: not found

**Comment by chen-shang** [comment]
你好，可以加我微信或者qq,我帮你看一下

**Comment by HeyGoda** [comment]
哦，怎么加你？

**Comment by chen-shang** [comment]
微信号:Xo_oX521

**Comment by chen-shang** [comment]
你用bash替换sh执行一下试试
